import { PerceptronSimulation }      from '../simulations/perceptron/index.js';
import { NNSimulation }              from '../simulations/nn/index.js';
import { LinearRegressionSimulation } from '../simulations/linearRegression/index.js';
import { DecisionTreeSimulation }    from '../simulations/decisionTree/index.js';
import { AdaBoostSimulation }        from '../simulations/adaboost/index.js';

export const simulations = [
  {
    id: 'perceptron',
    title: 'Perceptron',
    class: PerceptronSimulation,
    taskType: 'classification',
    metricKeys: ['loss', 'accuracy', 'recall', 'precision', 'f1'],
    defaultParams: {
      learningRate: 0.1,
      epochs: 100,
      nPoints: 120,
      seed: 42,
    },
    paramControls: [
      { name: 'learningRate', label: 'Learning Rate', type: 'number', min: 0.001, max: 1, step: 0.001,
        description: 'Controls weight update magnitude. Higher = faster but may overshoot.' },
      { name: 'epochs',       label: 'Epochs',        type: 'number', min: 1,     max: 500, step: 1,
        description: 'Number of complete passes through the training data.' },
      { name: 'nPoints',      label: 'Points',        type: 'number', min: 20,    max: 1000, step: 10,
        description: 'Number of training data points to generate.' },
      { name: 'seed',         label: 'Random Seed',   type: 'number', min: 0,     max: 9999, step: 1,
        description: 'Seed for reproducible data generation.' },
    ],
  },
  {
    id: 'nn',
    title: 'Neural Network (2-layer)',
    class: NNSimulation,
    taskType: 'classification',
    metricKeys: ['loss', 'accuracy', 'recall', 'precision', 'f1'],
    defaultParams: {
      learningRate: 0.1,
      epochs: 200,
      nPoints: 150,
      hiddenUnits: 4,
      seed: 42,
    },
    paramControls: [
      { name: 'learningRate', label: 'Learning Rate', type: 'number', min: 0.001, max: 1,    step: 0.001,
        description: 'Controls how much weights are updated each step.' },
      { name: 'epochs',       label: 'Epochs',        type: 'number', min: 1,     max: 1000,  step: 1,
        description: 'Number of complete passes through the training data.' },
      { name: 'hiddenUnits',  label: 'Hidden Units',  type: 'number', min: 1,     max: 20,    step: 1,
        description: 'Neurons in the hidden layer. More units = more complex boundaries.' },
      { name: 'nPoints',      label: 'Points',        type: 'number', min: 20,    max: 1000,  step: 10,
        description: 'Number of training data points.' },
      { name: 'seed',         label: 'Random Seed',   type: 'number', min: 0,     max: 9999,  step: 1,
        description: 'Seed for reproducible results.' },
    ],
  },
  {
    id: 'linearRegression',
    title: 'Linear Regression',
    class: LinearRegressionSimulation,
    taskType: 'regression',
    metricKeys: ['loss', 'mae', 'rmse', 'mape', 'nmae'],
    defaultParams: {
      learningRate: 0.1,
      epochs: 100,
      nPoints: 100,
      noise: 0.3,
      seed: 42,
    },
    paramControls: [
      { name: 'learningRate', label: 'Learning Rate', type: 'number', min: 0.001, max: 1,    step: 0.001,
        description: 'Gradient descent step size. Too high causes divergence.' },
      { name: 'epochs',       label: 'Epochs',        type: 'number', min: 1,     max: 500,  step: 1,
        description: 'Number of gradient descent iterations.' },
      { name: 'noise',        label: 'Noise Level',   type: 'number', min: 0.05,  max: 0.9,  step: 0.05,
        description: 'Noise added to the linear pattern. Higher = messier data.' },
      { name: 'nPoints',      label: 'Points',        type: 'number', min: 20,    max: 1000, step: 10,
        description: 'Number of training data points.' },
      { name: 'seed',         label: 'Random Seed',   type: 'number', min: 0,     max: 9999, step: 1,
        description: 'Seed for reproducible data generation.' },
    ],
  },
  {
    id: 'decisionTree',
    title: 'Decision Tree (recursive)',
    class: DecisionTreeSimulation,
    taskType: 'classification',
    metricKeys: ['loss', 'accuracy', 'recall', 'precision', 'f1'],
    defaultParams: {
      maxDepth: 6,
      minLeafSize: 5,
      nPoints: 120,
      seed: 42,
    },
    paramControls: [
      { name: 'maxDepth',     label: 'Max Depth',     type: 'number', min: 1, max: 10, step: 1,
        description: 'Maximum depth of the recursive tree. Each step adds one more level.' },
      { name: 'minLeafSize',  label: 'Min Leaf Size', type: 'number', min: 2, max: 40, step: 1,
        description: 'Minimum samples required to split a node. Higher = simpler tree.' },
      { name: 'nPoints',      label: 'Points',        type: 'number', min: 20, max: 1000, step: 10,
        description: 'Number of training data points.' },
      { name: 'seed',         label: 'Random Seed',   type: 'number', min: 0,  max: 9999, step: 1,
        description: 'Seed for reproducible data generation.' },
    ],
  },
  {
    id: 'adaboost',
    title: 'AdaBoost (Ensemble)',
    class: AdaBoostSimulation,
    taskType: 'classification',
    metricKeys: ['loss', 'accuracy', 'recall', 'precision', 'f1'],
    defaultParams: {
      epochs: 20,
      nPoints: 120,
      seed: 42,
    },
    paramControls: [
      { name: 'epochs',  label: 'Boosting Rounds', type: 'number', min: 1, max: 60, step: 1,
        description: 'Number of weak learners (decision stumps) to add to the ensemble.' },
      { name: 'nPoints', label: 'Points',          type: 'number', min: 20, max: 1000, step: 10,
        description: 'Number of training data points. Point size shows sample weight.' },
      { name: 'seed',    label: 'Random Seed',     type: 'number', min: 0,  max: 9999, step: 1,
        description: 'Seed for reproducible data generation.' },
    ],
  },
];
